// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtmGPqTSxRiKVuHfAz2mPz1cHpNVMywP8',
    appId: '1:14120582728:web:7b84bcfe823826b181227d',
    messagingSenderId: '14120582728',
    projectId: 'aduane-intelligence',
    authDomain: 'aduane-intelligence.firebaseapp.com',
    storageBucket: 'aduane-intelligence.firebasestorage.app',
    measurementId: 'G-K8QVJKZ2Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7yDpJZIFj410mT1UVSTn61j1pqyID2wE',
    appId: '1:14120582728:android:2327eb41fcb8ac9181227d',
    messagingSenderId: '14120582728',
    projectId: 'aduane-intelligence',
    storageBucket: 'aduane-intelligence.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgmmZO-rZS-twkMdPV98s2pd3yknioS4E',
    appId: '1:14120582728:ios:0386b124ccc99e1e81227d',
    messagingSenderId: '14120582728',
    projectId: 'aduane-intelligence',
    storageBucket: 'aduane-intelligence.firebasestorage.app',
    iosBundleId: 'com.example.capstoneFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgmmZO-rZS-twkMdPV98s2pd3yknioS4E',
    appId: '1:14120582728:ios:0386b124ccc99e1e81227d',
    messagingSenderId: '14120582728',
    projectId: 'aduane-intelligence',
    storageBucket: 'aduane-intelligence.firebasestorage.app',
    iosBundleId: 'com.example.capstoneFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtmGPqTSxRiKVuHfAz2mPz1cHpNVMywP8',
    appId: '1:14120582728:web:c68a35ebb8d8f77581227d',
    messagingSenderId: '14120582728',
    projectId: 'aduane-intelligence',
    authDomain: 'aduane-intelligence.firebaseapp.com',
    storageBucket: 'aduane-intelligence.firebasestorage.app',
    measurementId: 'G-Z7CV4KGYCW',
  );
}
