// File generated by FlutterFire CLI & customized for Aduane Intelligence (.env integration)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.get('FIREBASE_WEB_API_KEY'),
        appId: dotenv.get('FIREBASE_WEB_APP_ID'),
        messagingSenderId: dotenv.get('FIREBASE_SENDER_ID'),
        projectId: dotenv.get('FIREBASE_PROJECT_ID'),
        authDomain: '${dotenv.get('FIREBASE_PROJECT_ID')}.firebaseapp.com',
        storageBucket: '${dotenv.get('FIREBASE_PROJECT_ID')}.firebasestorage.app',
        measurementId: dotenv.get('FIREBASE_WEB_MEASUREMENT_ID'),
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.get('FIREBASE_ANDROID_API_KEY'),
        appId: dotenv.get('FIREBASE_ANDROID_APP_ID'),
        messagingSenderId: dotenv.get('FIREBASE_SENDER_ID'),
        projectId: dotenv.get('FIREBASE_PROJECT_ID'),
        storageBucket: '${dotenv.get('FIREBASE_PROJECT_ID')}.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.get('FIREBASE_IOS_API_KEY'),
        appId: dotenv.get('FIREBASE_IOS_APP_ID'),
        messagingSenderId: dotenv.get('FIREBASE_SENDER_ID'),
        projectId: dotenv.get('FIREBASE_PROJECT_ID'),
        storageBucket: '${dotenv.get('FIREBASE_PROJECT_ID')}.firebasestorage.app',
        iosBundleId: dotenv.get('FIREBASE_IOS_BUNDLE_ID', fallback: 'com.example.capstone_frontend'),
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.get('FIREBASE_IOS_API_KEY'),
        appId: dotenv.get('FIREBASE_IOS_APP_ID'),
        messagingSenderId: dotenv.get('FIREBASE_SENDER_ID'),
        projectId: dotenv.get('FIREBASE_PROJECT_ID'),
        storageBucket: '${dotenv.get('FIREBASE_PROJECT_ID')}.firebasestorage.app',
        iosBundleId: dotenv.get('FIREBASE_IOS_BUNDLE_ID', fallback: 'com.example.capstone_frontend'),
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.get('FIREBASE_WEB_API_KEY'),
        appId: dotenv.get('FIREBASE_WINDOWS_APP_ID'),
        messagingSenderId: dotenv.get('FIREBASE_SENDER_ID'),
        projectId: dotenv.get('FIREBASE_PROJECT_ID'),
        authDomain: '${dotenv.get('FIREBASE_PROJECT_ID')}.firebaseapp.com',
        storageBucket: '${dotenv.get('FIREBASE_PROJECT_ID')}.firebasestorage.app',
        measurementId: dotenv.get('FIREBASE_WINDOWS_MEASUREMENT_ID'),
      );
}